We are performing linear regression and finding the optimal parameters (weights and bias) that best fit the input data

Firstly we are doing the manual approch, without using any prebuild libraries.

In [22]:
import numpy as np
import pandas as pd

In [23]:
# np.random.seed(5)
#this is the input x 
# we can see that there 2 features ( in form of 2 coloumns)
x=np.array([[5,3],[6,4],[7,6],[9,8]])
x

array([[5, 3],
       [6, 4],
       [7, 6],
       [9, 8]])

In [24]:
#this the output varible

y=np.array([2,4,7,8])
y=y.reshape(-1,1)
y

array([[2],
       [4],
       [7],
       [8]])

In [25]:
indf=pd.DataFrame()

indf['X1']=x[:,0]
indf['X2']=x[:,1]
indf['Target Var']=y

This is how our input and output variables looks like in tablular form , for now to learn the concepts were are using less data

Here we have 2 features x1 and x2 and one target variable

In [26]:
indf

X1  X2  Target Var
0   5   3           2
1   6   4           4
2   7   6           7
3   9   8           8

In [27]:
x.shape

(4, 2)

In [28]:
def LRG(x,y,lr,epoch):
    m=x.shape[0]#number of trainning examples
    nx=x.shape[1]#number of features
    lr=0.01#learning rate

    w=np.zeros(shape=(nx,1))#initialing weights
    b=0
    cost_history=[]
    for i in range(epoch):
        
        yhat=np.dot(x,w)+b #prediction , order of dot is important , it should be x,w only
        error=yhat-y #error from the og y
        cost=np.dot(error.T,error)/(2*m) #this is standard formula for calculating and minimize the MSE in linear regression.
        
        dw=np.dot(x.T,error)/m #change in cost due to change in w (weights)
        db= np.sum(error)/m #change in cost due to change in b (bias)
        
        #these both updates the old value of w and b with new updated values
        w=w-(lr*dw)
        b=b-(lr*db)
        
        cost_history.append(cost) #we are storing the loss or error or mse in the list , so that later we check if the cost is minized by plotting it 
        
    return w,b # we are returning the final parameters

In [29]:
output=LRG(x,y,0.01,1000)

The first value in X is the optimum value of the bias and the second value is array with 2 elements which are the optimum weights for both the features (w1 and w2)

In [30]:
output

(array([[-0.32492419],
        [ 1.46913743]]),
 -0.2842943865158093)

We can make similar model using prebuild ML libraries , like we are using Sklearn below

In [33]:
import sklearn.linear_model as lm
lr = lm.LinearRegression()
lr.fit(x,y)
print(f'Optimum Bias:{lr.intercept_} \nOptimum Weights:{lr.coef_}')

Optimum Bias:[3.6] 
Optimum Weights:[[-1.7  2.5]]


Using similar approch, we can build a model for logistic regression also by chaning the cost function in this code