We are performing logistic regression and finding the optimal parameters (weights and bias) that best fit the input data

In [65]:
import pandas as pd
import numpy as np

In [66]:
x=np.array([[1.,2.,-1.],[3.,4.,-3.2]])
x

array([[ 1. ,  2. , -1. ],
       [ 3. ,  4. , -3.2]])

In [67]:
x=x.T
x

array([[ 1. ,  3. ],
       [ 2. ,  4. ],
       [-1. , -3.2]])

In [68]:
y=np.array([[1,0,1]])
print(y)
y=y.T
y

[[1 0 1]]


array([[1],
       [0],
       [1]])

In [69]:
indf=pd.DataFrame()
indf['X1']=x[:,0]
indf['X2']=x[:,1]
indf['Target Var']=y
indf

X1   X2  Target Var
0  1.0  3.0           1
1  2.0  4.0           0
2 -1.0 -3.2           1

In [70]:
x.shape

(3, 2)

In [71]:
m=x.shape[0]
nx=x.shape[1]
print(m,nx)

3 2


In [72]:
w=np.random.randint(1,5,nx)
w

array([1, 3])

In [73]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [88]:
def logistic_regression(x,y,lr,epooch):
    m=x.shape[0]
    nx=x.shape[1]
    w=np.random.rand(nx,1)
    b=np.random.randint(1,4)
    cost_history=[]
    for i in range(epooch):
        z=np.dot(x,w)+b
        a=sigmoid(z)
        
        error=a-y
        cost_function=-((np.sum(y*np.log(a)+(1-y)*np.log(1-a)))/m)
        
        dw=np.dot(x.T,error)/m

        db=np.sum(error)/m
        
        w=w-lr*dw
        b=b-lr*db
        
        cost_history.append(cost_function)
    return w,b

In [89]:
logistic_regression(x,y,0.009,1000)

(array([[-0.59917288],
        [-0.46826663]]),
 2.25665974272826)